spring:
  datasource:
    url: jdbc:h2:mem:airline;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  error:
    include-message: always

app:
  security:
    jwt-secret: 8I6rONQd4DXvXr2Yh51Ty4SVcnM4PT8ScD6hWCMb8ow=
    jwt-expiration-minutes: 180
  booking:
    hold-minutes: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info
